### ISSUE TITLE
django.db.utils.InternalError: Packet sequence number wrong - got 1 expected 0

### ISSUE THREAD

**Issue by PvauLy** [ScrappyZhang/python_web_Crawler_DA_ML_DL#6]
运行 python manage.py makemigrations 为模型的改变生成迁移文件时出现了这个错误：
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/data/env/pyweb/lib/python3.6/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/core/management/base.py", line 440, in execute
    self.check()
  File "/data/env/pyweb/lib/python3.6/site-packages/django/core/management/base.py", line 478, in check
    include_deployment_checks=include_deployment_checks,
  File "/data/env/pyweb/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/models/base.py", line 1181, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/models/base.py", line 1258, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 934, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 207, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 306, in _check_backend_specific_checks
    return connection.validation.check_field(self, **kwargs)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 18, in check_field
    field_type = field.db_type(connection)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 614, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 196, in data_types
    if self.features.supports_microsecond_precision:
  File "/data/env/pyweb/lib/python3.6/site-packages/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/mysql/features.py", line 52, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 371, in mysql_version
    with self.temporary_connection():
  File "/usr/local/python3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/base/base.py", line 462, in temporary_connection
    cursor = self.cursor()
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/data/env/pyweb/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/data/env/pyweb/lib/python3.6/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/data/env/pyweb/lib/python3.6/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/data/env/pyweb/lib/python3.6/site-packages/pymysql/connections.py", line 935, in connect
    self._get_server_information()
  File "/data/env/pyweb/lib/python3.6/site-packages/pymysql/connections.py", line 1249, in _get_server_information
    packet = self._read_packet()
  File "/data/env/pyweb/lib/python3.6/site-packages/pymysql/connections.py", line 1005, in _read_packet
    % (packet_number, self._next_seq_id))
django.db.utils.InternalError: Packet sequence number wrong - got 1 expected 0
请问有什么办法解决吗？期待你的回复

**Comment by AboveColin** [comment]
did you manage to fix this? and if so how?
